# Generated by Django 3.1.7 on 2021-02-25 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='locality',
            field=models.CharField(default=None, max_length=20, null=True),
        ),
    ]
