# Generated by Django 3.1.7 on 2021-02-28 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Notify',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receiver', models.CharField(max_length=30)),
                ('content', models.CharField(max_length=100)),
                ('service_request', models.CharField(max_length=200)),
                ('type', models.CharField(default='PENDING', max_length=20)),
            ],
        ),
    ]
