# Generated by Django 3.1.7 on 2021-02-28 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Services',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_type', models.CharField(max_length=30)),
                ('summary', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=200)),
                ('client_id', models.CharField(max_length=20)),
                ('provider_id', models.CharField(default=None, max_length=20, null=True)),
                ('status', models.CharField(default='PENDING', max_length=20)),
            ],
        ),
    ]
